AlgorithmsWebApp/Models/AlgorithmModels.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace AlgorithmsWebApp.Models
{
    public class AlgorithmModels

    {
        [Required(ErrorMessage = "Must select an algorithm.")]
        public AlgorithmSelection SelectedAlgorithm { get; set; }

        [Required(ErrorMessage = "Must select an algorithm.")]
        public List<SelectListItem> AlgorithmList = new List<SelectListItem>
        {
            new SelectListItem(AlgorithmSelection.BinarySearch.ToString(), ((int)AlgorithmSelection.BinarySearch).ToString()),
            new SelectListItem(AlgorithmSelection.CreateSinglyLinkedList.ToString(), ((int)AlgorithmSelection.CreateSinglyLinkedList).ToString()),
            new SelectListItem(AlgorithmSelection.InsertingNodeSinglyLinkedList.ToString(), ((int)AlgorithmSelection.InsertingNodeSinglyLinkedList).ToString())

        };

        
        public string? Collection { get; set; }

        public int TargetValue { get; set; }
    }
}

AlgorithmsWebApp/Models/AlgorithmSelection.cs
namespace AlgorithmsWebApp.Models
{
    public enum AlgorithmSelection
    {
        BinarySearch,
        CreateSinglyLinkedList,
        InsertingNodeSinglyLinkedList
    }
}

AlgorithmsWebApp/Models/DoublyLinkedNode.cs
namespace AlgorithmsWebApp.Models
{
    public class DoublyLinkedNode
    {
        public object Data;

        public DoublyLinkedNode Next;

        public DoublyLinkedNode Previous;

        public DoublyLinkedNode(object data = null, DoublyLinkedNode next = null, DoublyLinkedNode previous = null)
        {
            this.Data = data;
            this.Next = next;
            this.Previous = previous;
        }
    }
}

AlgorithmsWebApp/Models/ErrorViewModel.cs
namespace AlgorithmsWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AlgorithmsWebApp/Models/Node.cs
namespace AlgorithmsWebApp.Models
{
    public class Node
    {
        public object? Data;
        public Node? Next;

        public Node(object? data = null, Node? next = null)
        {
            Data = data;
            Next = next;
        }

        
    }
}

AlgorithmsWebApp/Models/ResultsModel.cs
namespace AlgorithmsWebApp.Models
{
    public class ResultsModel
    {
        public string ReturnedValue { get; set; }

        public string Explanation { get; set; }

        public string LinkToDocumentation { get; set; }

        public string InputCollection { get; set; }

        public string InputValue { get; set; }

        public ResultsModel(string returnedValue, string explanation, string linkToDocumentation, string inputCollection, string inputValue)
        {
            this.LinkToDocumentation = linkToDocumentation;
            this.ReturnedValue = returnedValue;
            this.Explanation = explanation;
            this.InputCollection = inputCollection;
            this.InputValue = inputValue;
        }
    }
}

AlgorithmsWebApp/Controllers/HomeController.cs
using AlgorithmsWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AlgorithmsWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AlgorithmsWebApp/Controllers/UserInputController.cs
using Microsoft.AspNetCore.Mvc;
using AlgorithmsWebApp.Models;
using AlgorithmsWebApp.Data;
using Newtonsoft.Json;
using System.IO;


namespace AlgorithmsWebApp.Controllers
{
    public class UserInputController : Controller
    {
        public UserInputController()
        {
            using (var sr = new StreamReader("AlgoInfo.txt"))
            {
                string line = null;

                while ((line = sr.ReadLine()) != null)
                {
                    if (!ResultsDisplayedToUser.TextToUserDictionary.ContainsKey(line))
                    {
                        ResultsDisplayedToUser.TextToUserDictionary.Add(line, sr.ReadLine());
                    }

                }
            }
        }
        public IActionResult Index()
        {
            var vm = new AlgorithmModels();

            return View(vm);
        }



        [HttpPost]
        public IActionResult AlgorithmSelected(AlgorithmModels vm)
        {
      
           return View(vm);
        }

        [HttpPost]
        public IActionResult GenerateResponse(AlgorithmModels am)
        {
           
            var AlgoOutput = am.SelectedAlgorithm switch
            {
                AlgorithmSelection.BinarySearch => Algorithms.BinarySearch(Algorithms.ParseToIntArray(am.Collection), am.TargetValue),
                _ => 0
            };

       
            ResultsModel results = new ResultsModel(AlgoOutput.ToString(), ResultsDisplayedToUser.TextToUserDictionary["BinarySearchDescription"].Trim(), ResultsDisplayedToUser.TextToUserDictionary["BinarySearchLink"].Trim(), am.Collection, am.TargetValue.ToString());


            ResultsDisplayedToUser.ResultsFromSession.Add(results);

            
            return View("index", am);
        }




    }
}

AlgorithmsWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AlgorithmsWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlgorithmsWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AlgorithmsWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="UserInput" asp-action="Index">AlgorithmsWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserInput" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AlgorithmsWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AlgorithmsWebApp/Views/UserInput/AlgorithmSelected.cshtml
@model AlgorithmModels;



<h1>AlgorithmSelected</h1>

<p>@Model.SelectedAlgorithm</p>

@if (@Model.SelectedAlgorithm.Equals(AlgorithmSelection.BinarySearch))
{
    <form method="post" asp-action="GenerateResponse" asp-controller="UserInput">

          <label for="valueToFind">Value To Find:</label>
          <input type="text" id="valueToFind" asp-for="TargetValue"><br><br>
          <label for="collectionOfValues">Collection Of Values (integers must be separated by a comma)</label>
          <input type="text" id="collectionOfValues" asp-for="Collection"><br><br>

          <input type="submit" value="Run" />
    </form>
}

else if (@Model.SelectedAlgorithm.Equals(AlgorithmSelection.CreateSinglyLinkedList)) //create a data structure, not run an algorithm 
{
    <form method="post" asp-action="GenerateResponse" asp-controller="UserInput">

          <label for="valueToFind">Value To Find:</label>
          <input type="text" id="valueToFind" asp-for="TargetValue"><br><br>
          <label for="collectionOfValues">Collection Of Values (integers must be separated by a comma)</label>
          <input type="text" id="collectionOfValues" asp-for="Collection"><br><br>

          <input type="submit" value="Run" />

    </form>
}

else if (@Model.SelectedAlgorithm.Equals(AlgorithmSelection.InsertingNodeSinglyLinkedList))
{
    <form method="post" asp-action="GenerateResponse" asp-controller="UserInput">

          <label for="valueToFind">Insertion Position:</label>
          <input type="text" id="valueToFind" asp-for="TargetValue"><br><br>
          <label for="collectionOfValues">Value of node to be inserted: </label>
          <input type="text" id="collectionOfValues" asp-for="Collection"><br><br>

          <input type="submit" value="Run" />

    </form>
}

else
{
    <p1>Not working</p1>
}

AlgorithmsWebApp/Views/UserInput/Index.cshtml
@using AlgorithmsWebApp.Models;
@using AlgorithmsWebApp.Data;
@model AlgorithmModels;


<div>
    <form method="post" asp-action="AlgorithmSelected" asp-controller="UserInput">

       
        <select required asp-for="SelectedAlgorithm">
            <option value="" disabled selected>--Select--</option>
            @foreach(var item in @Model.AlgorithmList)
            {
            <option value="@item.Text">@item.Text</option>
            }
        </select>


        <input type="submit" value="Run" />
    </form>
    
       @for(int i = ResultsDisplayedToUser.ResultsFromSession.Count - 1; i >= 0; i--) //iterate backwards to show most recent results first, avoid restructuring list each time
            {
                <hr class="dashed">
                <p>@Model.SelectedAlgorithm</p>
                <p>Input Value: @ResultsDisplayedToUser.ResultsFromSession[i].InputValue</p>
                <p>Input Collection: @ResultsDisplayedToUser.ResultsFromSession[i].InputCollection</p>
                <p>Output: @ResultsDisplayedToUser.ResultsFromSession[i].ReturnedValue</p>
                <p>Description of the @Model.SelectedAlgorithm algorithm:</P>
                <p>@ResultsDisplayedToUser.ResultsFromSession[i].Explanation</p>
                <p>Link to documentation:</P>
                <a href=@ResultsDisplayedToUser.ResultsFromSession[i].LinkToDocumentation target="_blank">Click Here</a>
            }

      
</div>